<a href="https://colab.research.google.com/github/aswanikrishnap/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [2]:
#please provide your answer below this line.
import numpy as np
matrix1 = np.random.randint(0,10,(3,3))
matrix2 = np.random.randint(0,10,(3,3)) 
print(matrix1)
print(matrix2)
dot = np.dot(matrix1,matrix2)
print(dot)

[[1 1 9]
 [6 8 7]
 [8 0 3]]
[[6 2 6]
 [9 8 9]
 [5 6 8]]
[[ 60  64  87]
 [143 118 164]
 [ 63  34  72]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [3]:
#please provide your answer below this line.
import numpy as np
matrix = [[55,25,15],[30,44,2],[11,45,77]]
print(matrix)
det = np.linalg.det(matrix)
print(det)

[[55, 25, 15], [30, 44, 2], [11, 45, 77]]
137180.0000000001
