<a href="https://colab.research.google.com/github/aswanikrishnap/Learn.py/blob/main/TASK_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For the given ndarray b below, evaluate whether elements in array, b are equal to 'red'.Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [9]:
#please type your answer below this line.
import numpy as np
b = np.array(["blue", "blue", "red", "blue"])
c='red'
b_bool = c == b
print(b_bool)

[False False  True False]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [3]:
#please type your answer below this line.
import numpy as np
a= np.arange(0,6)
b= np.arange(6,11)
print(np.append(a,b))

[ 0  1  2  3  4  5  6  7  8  9 10]


3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [4]:
#please type your answer below this line.
number1= np.arange(0,8)
number1= number1.reshape(2, 4)
number2= np.arange(8,16)
number2= number2.reshape(2, 4)
print(np.append(number1,number2,axis=0))
print(np.append(number1,number2,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
