<a href="https://colab.research.google.com/github/aswanikrishnap/Learn.py/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [3]:
#please type your answer below this line.
import numpy as np
mat1 = np.random.randint(0,8,(3,3))
mat2 = np.random.randint(10,19,(3,3))
print("Matrix A\n" ,mat1)
print("\nMatrix B\n" ,mat2) 
out = np.multiply.outer(mat1,mat2)
print("Outer Products\n",out)
dot = np.dot(mat1,mat2)
print("Dot Products\n",dot) 
Ele = np.multiply(mat1,mat2)
print("Element Wise\n",Ele)

Matrix A
 [[4 7 3]
 [6 7 6]
 [0 4 1]]

Matrix B
 [[17 18 12]
 [17 11 16]
 [14 14 12]]
Outer Products
 [[[[ 68  72  48]
   [ 68  44  64]
   [ 56  56  48]]

  [[119 126  84]
   [119  77 112]
   [ 98  98  84]]

  [[ 51  54  36]
   [ 51  33  48]
   [ 42  42  36]]]


 [[[102 108  72]
   [102  66  96]
   [ 84  84  72]]

  [[119 126  84]
   [119  77 112]
   [ 98  98  84]]

  [[102 108  72]
   [102  66  96]
   [ 84  84  72]]]


 [[[  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[ 68  72  48]
   [ 68  44  64]
   [ 56  56  48]]

  [[ 17  18  12]
   [ 17  11  16]
   [ 14  14  12]]]]
Dot Products
 [[229 191 196]
 [305 269 256]
 [ 82  58  76]]
Element Wise
 [[ 68 126  36]
 [102  77  96]
 [  0  56  12]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [5]:
#please type your answer below this line.
import numpy as np
mat = np.random.randint(0,16,(4,4))
print("Matrix is \n", mat) 
#adding 4(scalar) to the matrix
scal = 2
addScal = mat + scal
print("\n Scalar Matrix\n",addScal) 
#matrix broadcasting
nums = np.array([1,2,3,4])
mult = mat * nums
print("\nThe Multiplication by broadcasting\n",mult)

Matrix is 
 [[12  2  7 11]
 [ 1 11  7 15]
 [ 5 12 13  0]
 [13 10 13  5]]

 Scalar Matrix
 [[14  4  9 13]
 [ 3 13  9 17]
 [ 7 14 15  2]
 [15 12 15  7]]

The Multiplication by broadcasting
 [[12  4 21 44]
 [ 1 22 21 60]
 [ 5 24 39  0]
 [13 20 39 20]]
