<a href="https://colab.research.google.com/github/aswanikrishnap/Learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [2]:
#please enter your code below this line.
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)
sum = np.sum(mat)
print("\n Sum is :\n",sum)


 The Matrix is:
 [[3 6 3]
 [2 2 1]
 [6 5 1]]

 Sum is :
 29


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [1]:
#please enter your code below this line.
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat) 
col = np.sum(mat,axis =0)
print("\n Sum of Columns:\n",col) 
row = np.sum(mat,axis =1)
print("\n Sum of Columns:\n",row)


 The Matrix is:
 [[7 5 5]
 [0 0 5]
 [5 3 2]]

 Sum of Columns:
 [12  8 12]

 Sum of Columns:
 [17  5 10]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [3]:
#please enter your code belowthis line.
import numpy as np
mat = np.random.randint(0,15,(4,4))
print("\n The Matrix is:\n",mat) 
min = np.min(mat)
print("\n Minimum Value is\n",min) 
max = np.max(mat)
print("\n Maximum Value is\n",max) 
mean = np.mean(mat)
print("\n Minimum Value is\n",mean)


 The Matrix is:
 [[ 6  3  8  4]
 [ 6 11  4 10]
 [14  7 10  8]
 [ 9  4 10  8]]

 Minimum Value is
 3

 Maximum Value is
 14

 Minimum Value is
 7.625


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [5]:
#please enter your code below this line.
import numpy as np
mat = np.random.randint(0,99,(10,10))
print("\n The Matrix is:\n",mat) 
print("\nThe 7th row is :\n",mat[7,:]) 
print("\nThe 4-8th row is :\n",mat[4:8,:]) 
print("\nThe value at (5,5) is :\n",mat[5,5]) 
print("\nThe 5th column) is :\n",mat[:,5])


 The Matrix is:
 [[78 42 25 17  8  3 41 73 35 30]
 [19 13 44 89 67 22 61 16  4 69]
 [71 39 41  3 35 55  2 59 10 87]
 [22  9 44 64 59  3 44 76 81 53]
 [77 89 69  5 41 87 40 11 63 57]
 [ 9 50 95 49  6 50 77 79 41 15]
 [42  4 91 10 47  4 40 65 41 32]
 [93 72 50 29  5 96 78  6 77 94]
 [38 98 57 62 81 59 98 39 32 18]
 [75 85 14 51 40 27 91 40 20 93]]

The 7th row is :
 [93 72 50 29  5 96 78  6 77 94]

The 4-8th row is :
 [[77 89 69  5 41 87 40 11 63 57]
 [ 9 50 95 49  6 50 77 79 41 15]
 [42  4 91 10 47  4 40 65 41 32]
 [93 72 50 29  5 96 78  6 77 94]]

The value at (5,5) is :
 50

The 5th column) is :
 [ 3 22 55  3 87 50  4 96 59 27]
