<a href="https://colab.research.google.com/github/aswanikrishnap/Learn.py/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [2]:
#please type your answer below this line.
import numpy as np 
mat = np.random.randint(0,15,(4,4))
print("Array\n",mat) 
print("Trace of the Array is: \n",mat.trace())

Array
 [[14  1  2  4]
 [ 4 11  5  5]
 [ 2 10 13  3]
 [10 12 11  2]]
Trace of the Array is: 
 40


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [1]:
#please type your answer below this line.
import numpy as np
mat = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Matix\n",mat)
print("\nThe Inverse of Matrix is :\n",np.linalg.inv(mat))

Matix
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The Inverse of Matrix is :
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [3]:
#please type your answer below this line.
import numpy as np 
mat = np.random.randint(0,8,(3,3))
print("Array\n",mat)
print("\nThe Norm of the Matrix is\n",np.linalg.norm(mat))

Array
 [[0 3 7]
 [0 5 0]
 [3 0 5]]

The Norm of the Matrix is
 10.816653826391969


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [4]:
#please type your answer below this line.
import numpy as np 
mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)
print("\nThe EigenValue and EigenVectors of the Matrix is\n",np.linalg.eig(mat))

Array
 [[11 10  4 14]
 [10  2  2 12]
 [ 2 13 13  9]
 [13 13 14 12]]

The EigenValue and EigenVectors of the Matrix is
 (array([39.309745  +0.j        ,  7.60411213+0.j        ,
       -4.45692856+2.09845149j, -4.45692856-2.09845149j]), array([[ 0.50937055+0.j        ,  0.52988594+0.j        ,
        -0.07925377-0.36508913j, -0.07925377+0.36508913j],
       [ 0.36672356+0.j        ,  0.34164117+0.j        ,
         0.65681044+0.j        ,  0.65681044-0.j        ],
       [ 0.43968904+0.j        , -0.76052216+0.j        ,
        -0.33226935-0.23431545j, -0.33226935+0.23431545j],
       [ 0.6424399 +0.j        , -0.1552683 +0.j        ,
        -0.23199181+0.45815059j, -0.23199181-0.45815059j]]))
